# Generated by Django 2.2 on 2019-05-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='attribute')),
                ('description', models.TextField(default='...', verbose_name='description')),
                ('start_min', models.IntegerField(default=80)),
                ('start_max', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('level', '?'),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('level_min', models.IntegerField(default=1)),
                ('level_max', models.IntegerField(default=100)),
                ('kind', models.CharField(choices=[('victory', 'victory'), ('failure', 'failure'), ('exit', 'exit')], max_length=8, verbose_name='kind')),
                ('percent', models.FloatField(default=10)),
            ],
            options={
                'ordering': ('?',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
                ('status', models.IntegerField(choices=[(0, 'begin'), (1, 'choices'), (2, 'text'), (3, 'victory'), (4, 'exit'), (5, 'error')], default=0)),
                ('level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='simplechoice.Event')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simplechoice.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simplechoice.Answer')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='simplechoice.Decision')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='simplechoice.Game')),
            ],
        ),
        migrations.CreateModel(
            name='GameAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('value_max', models.IntegerField(default=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='simplechoice.Attribute')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='simplechoice.Game')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('min', 'Min'), ('max', 'Max')], max_length=3, verbose_name='value kind')),
                ('value', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simplechoice.Attribute')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='simplechoice.Event')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionRequireAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('min', 'Min'), ('max', 'Max')], max_length=3, verbose_name='value kind')),
                ('value', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simplechoice.Attribute')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='simplechoice.Decision')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerGetAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='simplechoice.Answer')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='simplechoice.Attribute')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simplechoice.Decision'),
        ),
    ]
