# Generated by Django 2.2 on 2019-04-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='name')),
            ],
        ),
    ]
