# Generated by Django 2.2.1 on 2019-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevent',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
