# Generated by Django 2.2 on 2019-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
