# Generated by Django 2.2 on 2019-04-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190420_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Answer')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.Decision')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.Game')),
            ],
        ),
    ]
