# Generated by Django 2.2 on 2019-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gamedecision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('?', 'age')},
        ),
        migrations.AddField(
            model_name='decision',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
