# Generated by Django 2.2 on 2019-04-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190420_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('age', '?')},
        ),
        migrations.AddField(
            model_name='answer',
            name='result',
            field=models.TextField(default='', verbose_name='result'),
        ),
    ]
