# Generated by Django 2.2 on 2019-04-20 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190420_0432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=64, verbose_name='attribute')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='result',
        ),
        migrations.CreateModel(
            name='GameAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core.Attribute')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Game')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Answer')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.Attribute')),
            ],
        ),
    ]
