# Generated by Django 2.2 on 2019-04-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190420_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gameattribute',
            old_name='max',
            new_name='value_max',
        ),
        migrations.AddField(
            model_name='attribute',
            name='start_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='attribute',
            name='start_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
