# Generated by Django 2.2 on 2019-04-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190423_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('level', '?')},
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='age',
            new_name='level',
        ),
    ]
