# Generated by Django 2.2 on 2019-04-25 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190425_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('level_min', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExitAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('victory', 'victory'), ('failure', 'failure')], max_length=8, verbose_name='kind')),
                ('value_kind', models.CharField(choices=[('min', 'Min'), ('max', 'Max')], max_length=3, verbose_name='value kind')),
                ('value', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='core.Attribute')),
                ('exit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Exit')),
            ],
        ),
    ]
