# Generated by Django 2.2 on 2019-04-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exit_exitattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exitattribute',
            name='value_kind',
        ),
        migrations.AddField(
            model_name='exit',
            name='kind',
            field=models.CharField(choices=[('victory', 'victory'), ('failure', 'failure')], default='victory', max_length=8, verbose_name='kind'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exitattribute',
            name='kind',
            field=models.CharField(choices=[('min', 'Min'), ('max', 'Max')], max_length=3, verbose_name='value kind'),
        ),
    ]
