# Generated by Django 2.2 on 2019-04-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190425_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='percent',
            field=models.FloatField(default=10),
        ),
    ]
