# Generated by Django 2.2 on 2019-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_exit_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exit',
            options={'ordering': ('?',)},
        ),
        migrations.AddField(
            model_name='exit',
            name='level_max',
            field=models.IntegerField(default=100),
        ),
    ]
