# Generated by Django 2.2 on 2019-04-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190428_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionRequireAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('min', 'Min'), ('max', 'Max')], max_length=3, verbose_name='value kind')),
                ('value', models.IntegerField(default=1)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Attribute')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='require', to='core.Decision')),
            ],
        ),
        migrations.DeleteModel(
            name='AnswerRequireAttribute',
        ),
    ]
