# Generated by Django 2.2 on 2019-04-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190428_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answergetattribute',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Answer'),
        ),
        migrations.AlterField(
            model_name='decisionrequireattribute',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requires', to='core.Decision'),
        ),
    ]
