# Generated by Django 2.2 on 2019-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190428_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='text',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='kind',
            field=models.CharField(choices=[('victory', 'victory'), ('failure', 'failure'), ('exit', 'exit')], max_length=8, verbose_name='kind'),
        ),
    ]
